export const Data = [
    {
        id: 1,
        name: "Applied",
        data: [
            {
                id: 1,
                name: "Javier",
                paternal_last_name: "Amaya",
                job_title: "Backend Developer",
                email: "javier@amaya.com",
                cellphone: "573154654",
                city: 'Mérida',
                country: 'México',
                postulation_status: {
                    name: "applied",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
            {
                id: 2,
                name: "Kevin",
                paternal_last_name: "Cruz",
                job_title: "Fullstack Developer",
                email: "kevin@cruz.com",
                cellphone: "573154654",
                city: 'Bogota',
                country: 'Colombia',
                postulation_status: {
                    name: "applied",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
            {
                id: 3,
                name: "Daniel",
                paternal_last_name: "González",
                job_title: "Fullstack Developer",
                email: "daniel@gonzalez.com",
                cellphone: "573154654",
                city: 'Bogota',
                country: 'Colombia',
                postulation_status: {
                    name: "applied",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
        ],
    },
    {
        id: 2,
        name: "Interviews",
        data: [
            {
                id: 4,
                name: "Yadurani",
                paternal_last_name: "López",
                job_title: "Frontend Developer",
                email: "jadu@lopez.com",
                cellphone: "573154654",
                city: 'Bogota',
                country: 'Colombia',
                postulation_status: {
                    name: "interviews",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
            {
                id: 5,
                name: "Fernando",
                paternal_last_name: "de Leon",
                job_title: "Frontend Developer",
                email: "fercho@leon.com",
                cellphone: "573154654",
                city: 'Bogota',
                country: 'Colombia',
                postulation_status: {
                    name: "interviews",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
            {
                id: 6,
                name: "Leonardo",
                paternal_last_name: "Espinoza",
                job_title: "Reactjs Developer",
                email: "leo@espinoza.com",
                cellphone: "573154654",
                city: 'Bogota',
                country: 'Colombia',
                postulation_status: {
                    name: "interviews",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
        ],
    },
    {
        id: 3,
        name: "Accepted",
        data: [
            {
                id: 7,
                name: "Zajith",
                paternal_last_name: "Corro",
                job_title: "Frontend Developer",
                email: "zajith@corro.com",
                cellphone: "573154654",
                city: 'Mérida',
                country: 'México',
                postulation_status: {
                    name: "accepted",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
            {
                id: 8,
                name: "Jimmy",
                paternal_last_name: "Anaya",
                job_title: "PHP Developer",
                email: "jimmy@anaya.com",
                cellphone: "573154654",
                city: 'Bucaramanga',
                country: 'Colombia',
                postulation_status: {
                    name: "accepted",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
            {
                id: 9,
                name: "Diego",
                paternal_last_name: "Lozano",
                job_title: "PHP Developer",
                email: "diego@lozano.com",
                cellphone: "573154654",
                city: 'Bogota',
                country: 'Colombia',
                postulation_status: {
                    name: "accepted",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
        ],
    },
    {
        id: 4,
        name: "Rejected",
        data: [
            {
                id: 10,
                name: "Camilo",
                paternal_last_name: "Cruz",
                job_title: "JavaScript Developer",
                email: "camilo@cruz.com",
                cellphone: "573154654",
                city: 'Bogota',
                country: 'Colombia',
                postulation_status: {
                    name: "rejected",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
            {
                id: 11,
                name: "Felipe",
                paternal_last_name: "Ramírez",
                job_title: "Angular Developer",
                email: "felipe@ramirez.com",
                cellphone: "573154654",
                city: 'Medellín',
                country: 'Colombia',
                postulation_status: {
                    name: "rejected",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
            {
                id: 12,
                name: "David",
                paternal_last_name: "Camargo",
                job_title: "JavaScript Developer",
                email: "david@camargo.com",
                cellphone: "573154654",
                city: 'Bogota',
                country: 'Colombia',
                postulation_status: {
                    name: "rejected",
                    created_at: "2022-02-17T19:10:45",
                    updated_at: "2022-02-17T19:10:45",
                },
                vacancy_id: 1,
            },
        ],
    }
];